### ISSUE TITLE
D405 6D pose

### ISSUE THREAD

**Issue by HM102** [haritheja-e/robot-utility-models#2]
How do you collect 6D pose from the d405 camera without using SLAM?

Also you mentioned that using iPhone you get rid of the SLAM pipeline used in other papers. How the does iPhone gets the 6D pose, doesn't use internally some kind of visual inertial system as well?

Thank you.

**Comment by notmahi** [comment]
Hi @HM102! We only collect 6D pose from the iPhone Pro, and not from the D405.

The iPhone Pro offers the [ARKit API](https://developer.apple.com/documentation/arkit/), which in their own words "combines device motion tracking, world tracking, (and) scene understanding". Because it is fusing a lot more sensors, it is a lot more robust than just using visual SLAM.
