### ISSUE TITLE
xarm7

### ISSUE THREAD

**Issue by Nimingez** [haritheja-e/robot-utility-models#6]
Thank you for sharing such great work. Could you please introduce how to use the code for xArm7？ My robot is UR5

**Comment by Nimingez** [comment]
from robot.utils import create_transform, transform_to_vec
no create_transform, transform_to_vec?

**Comment by haritheja-e** [comment]
Hi! Thank you for your interest in our work. We just pushed an update including those functions; it seems an outdated file was pushed previously. Thank you for catching this! 

To run policies on a UR5, you would first need to mount our [gripper](https://robotutilitymodels.com/#hardware) onto it, which would need to include a XL430 Dynamixel motor for actuation as well as an iPhone. We don’t have access to a UR5, so we haven’t made a mount for it, but you should be able to use the [xArm 7 mount](https://drive.google.com/drive/u/1/folders/1l90ln_h95Drs8IGhy1ySoNtZxB0igSR3) as a reference and create a new mount. 

In terms of using the xArm code, you’d just need to set the following configs in robot-server [start_server.yaml](https://github.com/haritheja-e/robot-utility-models/blob/main/robot-server/configs/start_server.yaml) defaults: “controller: xarm” and “camera: iphone”. Also, the xArm ip would need to be set in [network.yaml](https://github.com/haritheja-e/robot-utility-models/blob/main/robot-server/configs/network/network.yaml). Then, the [documentation](https://educated-diascia-662.notion.site/Setting-Up-Running-Zero-Shot-Models-on-Hello-Robot-Stretch-66658ab1a6454f219e0fb1db1baa9d6f) for running policies should largely follow once the gripper Dynamixel is also connected (the robot server would need to be run in a conda/mamba environment containing the arm's controller package). 

To run the policies on the xArm, we add in a transform from the iPhone position to end-effector, then convert the policy's relative action from iPhone coordinate frame to xArm coordinate frame, and finally use the robot’s IK to execute the relative action. The same steps should be able to be performed on a UR5. 

We also no longer have this xArm/gripper setup in our lab, but please let me know if you face any issues and I’d be glad to set it back up again to help debug if needed.

**Comment by Nimingez** [comment]
Thank you for your patient response. I would like to ask how I can determine the positions of the end effector and the phone. The coordinate system of my robotic arm's end effector is as follows:
![11](https://github.com/user-attachments/assets/e168fb1e-fc4e-476e-af52-3b87a1758e72)

**Comment by Nimingez** [comment]
How can I make the model execute the task all at once instead of manually performing it step by step?

**Comment by haritheja-e** [comment]
Great question! Using the `robot-server` and `imitation-in-homes` code from the **`gpt_retry`** branch, rather than `main`, would be better for having the task perform all at once, as the UI doesn't currently support this functionality. Running `run.py` on `gpt_retry` branch does not provide the UI to run policies, and you can instead easily run them through the command line. I've included some commands for running below: 

- h + ↵: home the robot
- r + ↵: change home height of the robot
- ↵: takes 1 step of the policy
- [integer n] + ↵: takes n steps of the policy
- e + ↵: auto-runs evaluation using gpt retrying (if the use_gpt config is set and API key is provided)
- q + ↵: quits the process

For example, 10 + ↵ would execute 10 steps of the policy consecutively, rather than needing to manually step through. e + ↵ will use a fixed time horizon set by the `TIME_HORIZON` variable, and run the policy until the time limit is reached, this way you also do not need to perform it step-by-step. 

The reason we often run step-by-step is that our primary robot, the Hello Robot Stretch, does not having a very good blocking controller. Its low-level controllers also do not move linearly from current to desired pose, so we aren't able to simply run our policies at a higher frequency, and must wait until the current action is complete before performing the next. The methods I mentioned above ([integer n] + ↵ and e + ↵) use time.sleep() in order to achieve this.
