### ISSUE TITLE
whether the setup and running steps for the xArm robot are the same as those described here for the Hello Robot Stretch

### ISSUE THREAD

**Issue by 2814894078** [haritheja-e/robot-utility-models#8]
Hello, thank you for providing the detailed documentation for setting up and running the zero-shot models on the Hello Robot Stretch. I wanted to confirm whether the setup and running steps for the xArm robot are the same as those described here for the Hello Robot Stretch. If there are any differences, could you please clarify? Additionally, if our xArm gripper model is different from the one you are using, would the process still be compatible or feasible? Thank you for your help!

**Comment by haritheja-e** [comment]
Hi! Thank you for your interest. The setup and running process for the xArm is largely the same, but some differences are detailed below: 

First, you’d need to set the following configs in robot-server [start_server.yaml](https://github.com/haritheja-e/robot-utility-models/blob/main/robot-server/configs/start_server.yaml) defaults: “controller: xarm” and “camera: iphone”. Also, the xArm ip would need to be set in [network.yaml](https://github.com/haritheja-e/robot-utility-models/blob/main/robot-server/configs/network/network.yaml). Then, the [documentation](https://educated-diascia-662.notion.site/Setting-Up-Running-Zero-Shot-Models-on-Hello-Robot-Stretch-66658ab1a6454f219e0fb1db1baa9d6f) for running policies should largely follow once the gripper Dynamixel is also connected. Also, the robot server would need to be run in a conda environment containing the xArm's controller package. 

Unfortunately, our policies are currently limited to the custom gripper used on our data collection tool, so that will need to be attached using a 3D printed xArm mount: https://github.com/haritheja-e/robot-utility-models/tree/main/hardware/xArmMount. An iPhone will also need to be attached to the mount using our [phone holder](https://github.com/haritheja-e/robot-utility-models/tree/main/hardware/stickV2/phoneHolder). 

Also, just a note: we no longer have this xArm/gripper setup in our lab, but please let me know if you face any issues and I'll see if I can set it back up again to help debug if needed. If you have any additional questions, let us know!
